### ISSUE TITLE
IDEA test

### ISSUE THREAD

**Issue by zlemon819** [carbynestack/mp-spdz-integration#16]
hi， i want to test this project in IDEA, what is the dependency “common-testing” in pom.xml? It seems not accessible by Maven repositories. Thank you.

**Comment by strieflin** [comment]
Hi @zlemon819, the dependency is from [carbynestack/common](https://github.com/carbynestack/common). It _is_ available via the Github maven registry (see [here](https://github.com/carbynestack/common/packages/1092945)). You should provide more context (at least the maven error message) to enable us to help you diagnosing the problem.

**Comment by sbckr** [comment]
Hello @zlemon819.
Thank you for your interest in Carbyne Stack and reaching out to us with your question on common-testing.

The mentioned dependency is build as part of our [common](https://github.com/carbynestack/common) repository and published on GitHub Packages (see [io.carbynestack.common-testing](https://github.com/carbynestack/common/packages/1092945).

As of now, the GitHub Package registry requires authentication to download(install) artifacts (see [Working with the Apache Maven registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-to-github-packages). We are aware that this fact can cause problems if someone wants to try and build CS themselves, and are therefore evaluating other options.

In order to download the Carbyne Stack dependencies with Maven in the meantime, it is required to define your GitHub credentials in Maven.
Your `~/.m2/settings.xml` should look similar to the following:

```xml
<settings>
    <profiles>
        <profile>
            <id>github</id>
            <repositories>
                <repository>
                    <id>github</id>
                    <url>https://maven.pkg.github.com/carbynestack/*</url>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                </repository>
            </repositories>
        </profile>
    </profiles>
    

    <activeProfiles>
            <activeProfile>github</activeProfile>
    </activeProfiles>

    <servers>  
        <server>
      	     <id>github</id>
      	     <username>{{YOUR GITHUB USERNAME}}</username>
      	     <password>{{GITHUB PAT WITH PACKAGE READ SCOPE}}</password>
      	</server>
    </servers>
</settings>
```

Please let me know in case you need any further support.

**Comment by strieflin** [comment]
Seems to be resolved. Closing this.
